import type { Metadata } from "next";
import "./globals.css";
import ScrollAnimationWrapper from "@/components/Landing/ScrollAnimationWrapper";
import StripeProvider from "@/components/StripeProvider";
import ReownProvider from "@/components/ReownProvider";
import { CurrencyProvider } from "@/context/CurrencyContext";
import { ReduxProvider } from "@/lib/store/provider";

export const metadata: Metadata = {
  title: "CHA $CHING",
  description: "Generated by create next app",
};

import { Toaster } from "react-hot-toast";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center" reverseOrder={false} />
        <ReownProvider>
          <ReduxProvider>
            <CurrencyProvider>
              <StripeProvider>
                <ScrollAnimationWrapper>{children}</ScrollAnimationWrapper>
              </StripeProvider>
            </CurrencyProvider>
          </ReduxProvider>
        </ReownProvider>
      </body>
    </html>
  );
}
